[package]
name = "hyprfocus"
version = "0.1.0"
edition = "2024"
description = "Hyprland focus logger CLI"
license = "MIT"

[dependencies]
chrono = "0.4.40"
colored = "3.0.0"
csv = "1.3.1"
terminal_size = "0.4.2"
